### ISSUE TITLE
Tests element is returning null

### ISSUE THREAD

**Issue by marvinhosea** [mayeedwin/mulika#1]
```Uncaught TypeError: Cannot read property 'appendChild' of null at Object.typeCheck (@latest.js:32) at index.html:59```

This error is caused because element assigned to tests returning null even after adding an element with ```id="tests"``

**Comment by mayeedwin** [comment]
Hey @marvinhosea, thanks for filing this. The missing part of the documentation is the html 
component for mulika. Ahsante sana. 

Kindly add the following snippet to the bottom of your html page...

```html
<section id="mulika" class="mulika">
    <div class="top">
        <div class="btns">
            <span class="circle red"></span>
            <span class="circle yellow"></span>
            <span class="circle green"></span>
            <span class="mulika-title">Mulika Tests</span>
        </div>
    </div>
    <pre class="tests" id="tests"></pre>
</section>
```

**Comment by mayeedwin** [comment]
@marvinhosea , let me know if this helped!

**Comment by marvinhosea** [comment]
```Uncaught TypeError: can't access property "style", terminal is null```

Still getting that error you

**Comment by mayeedwin** [comment]
Hey @marvinhosea,  I would love to see how you are setting up.  New updated setup-docs are up

And you are probably getting the error because you have added the component as the last thing in your page. Add the html component at the bottom of your html page in the body tag, **before any scripts in your page**.

cc @marvinhosea
